POST http://localhost:5000/api/login 
Content-Type: application/json

{
    "username": "Felix",
    "password": "TestPassword"
}

### 
POST http://localhost:5000/api/create 
Content-Type: application/json

{
    "username": "Christopher",
    "password": "TestPassword",
    "email": "hej@example.com",
    "newsletter": false
}


###

PUT http://localhost:5000/api/change
Content-Type: application/json

{
    "_id": "628b67440e5d2ea4eac82dc9",
    "newsletter": false
}

###

DELETE http://localhost:5000/products/