POST http://localhost:5000/api/login 
Content-Type: application/json

{
    "username": "Felix",
    "password": "TestPassword"
}

###

GET http://localhost:5000/api/login/628b42faeaed62de209d6dea

### 
POST http://localhost:5000/api/create 
Content-Type: application/json

{
    "username": "Anna",
    "password": "TestPassword",
    "email": "Anna@example.com",
    "newsletter": false
}


###

PUT http://localhost:5000/api/change
Content-Type: application/json

{
    "_id": "628b67440e5d2ea4eac82dc9",
    "newsletter": false
}

###

DELETE http://localhost:5000/products/